services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    # network_mode: host
    ports:
      - "9100:9100"
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    command:
      - --web.listen-address=:9100
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host

  promtail:
    image: grafana/promtail:2.9.4
    user: root
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml:Z
      - /var/log/journal:/var/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket
    restart: unless-stopped
